CREATE TABLE skills (
	skill_id INT,
	skill_name VARCHAR(255),
	skill_desc TEXT,
	skill_artifact VARCHAR(255),
	pipeline_id INT
);

INSERT INTO skills (skill_id, skill_name, skill_desc, 	skill_artifact, pipeline_id)
VALUES
(0,"introduction communicated clearly when presenting","Speaker kicks off the presentation by introducing themselves and their project through a one-liner of what it's about.","live",9),
(1,"modules used","After creating the wrangle module(s), you import those into your final report, so that you can use those functions you wrote to acquire and prepare your data with ease, with little clutter, and with reduced risk of running into issues when reproducing the report. The functions should be called to prepare your data (as opposed to re-writing the code of the functions in your notebook), and you should include in a markdown cell, a verbal explanation of the steps you took to prepare the data and why you made those decisions.","ipynb",3),
(2,"missing values addressed","Decisions made and reasons are communicated and documented for handling missing values. If you imputed based on a computed value (such as mean, median, etc), that was done after splitting the data, and the value was derived from the training dataset only and then imputed into all 3 datasets. If you filled missing values with 0 or a constant not derived from existing values, that can be done prior to splitting the data. ","py or ipynb",3),
(3,"data split into 3 samples avoiding data leakage","Data should always be split into three samples (Train, Validate, and Test) prior to exploration of variable relationships. In addition, imputers, scalers, feature elimination, and selection algorithms should all be run after the split, so they are fit on train and transform validate and test.","ipynb",3),
(4,"well designed analysis - ask a clear question, [discover], provide a clear answer.","Key questions asked and answered of the data are shared in the final report notebook. You should ask questions of the data using natural language that speaks to the business stakeholders in markdown cells, ideally a header prior to the visualization or statistical test, that you then explore. This does not take the place of stating your null hypothesis/alternative hypothesis when doing a statistical test, but those hypotheses are generally for you. By writing questions that you intend to answer with visualizations and statistical tests in natural language, like 'Are office supplies leading to differences in profit in Texas?', you are able to guide both yourself and your reader through the highlights of your analysis. You ask a question, create a visual, run a statistical test (if appropriate), and wrap it nicely with a markdown cell that contains a clear answer in layman's terms. You do all that before moving to the next question. ","ipynb",4),
(5,"questions answered using visual exploratory analysis","Visualizations are included in your final report. Those included answer a question (remember, 'no' is an answer) or provide necessary context (such as the distribution of the target variable). All statistical tests included in the final report should be supported with a visualization of the interaction of the tested variables. Charts in the final report should have titles and labels that are descriptive and useful for the end user/audience/consumer of the report. All visualizations in the final report are mentioned or discussed if a verbal presentation is given. ","ipynb",4),
(6,"questions answered using statistical analysis","Statistical tests are included in your final report. The correct tests are run, given the data type and distribution, and the correct conclusions are drawn.  - correlation: two continuous variables, normally distributed, testing for LINEAR correlation only (H_0: Not linearly dependent); - independent t-test: one continuous, somewhat normally distributed variable, one boolean variable, equal variance, independent (H_0: population mean of each group is equal); - chi-squared test: two discrete variables. (H_0: the two variables are independent of each other). (other tests may be used)","ipynb",4),
(7,"exploration summarized","Following your exploration section, you summarize your analysis (in a markdown cell using natural language): what you found and how you will use it moving forward. This includes key takeaways from all the questions answered in explore, a list of which features will be used in modeling and why, and which features will not move forward and why. You may only call out a few of these features in the presentation, but having that there for reference is important in a report. A group of features may have the same reason why, and those can be mentioned together.","ipynb",4),
(8,"in-sample evaluation of a variable-free baseline (train)","A baseline tells you whether a model you build using the features you selected performs any better than predicting by using only the target variable. In classification,  a baseline can be created by predicting only the most common outcome class, like predicting that all Titanic passengers will die becuase the majroity died. This results in the highest accuracy without using extra information from features. The baseline is based on the training dataset. For a continuous target variable, the baseline could be predicting that all salaries will be the median salary of our labeled train data. The predictions should be made on the training data (like the predicted value, y_hat, for all passengers 'survived' == 0) and then evaluated on validate to compare against your models. If any model you build does not perform better than a baseline that uses no features, then your features are not significant drivers of the outcome.","ipynb",6),
(9,"in-sample evaluation for model performance (train)","All models should be evaluated on train. The training sample is our largest sample, and we have to both fit the model on train and see how the model performs on it. We should never skip straight to validate. We would be missing out on valuable observations.","ipynb",6),
(10,"out-of-sample evaluation for overfitting (validate)","The top models should be evaluated with the validation sample dataset. It is important to use the validate sample for checking for any overfitting that may have occurred when fitting the model on train. If you are creating many models, it is also important to only validate a handful of your top models with the validate dataset. Otherwise, your data will have seen validate as much as train, and you could accidentally introduce some implicit bias based on data and results you see while validating so many models.","ipynb",6),
(11,"evaluation metric selected & supported ","You clearly communicate how you evaluated and compared models. What metric(s) did you use and why? For example, in one case, you may decide to use precision over accuracy. If so, why? If you use multiple metrics, how do you decide which to select if metric is better for model A but another metric is better for model B? Do you rank them? Do you find a way to aggregate them into a single metric? ","ipynb",6),
(12,"out-of-sample evaluation for expected future performance (test)","Your top performing model, and only your top performing model, should be evaluated on your test dataset. Evaluating only your final model on a test dataset allows you to estimate how the model will perform in the future on unseen data.","ipynb",6),
(13,"unique models developed","Models can differ based on the features used, the hyperparameters selected, and/or the algorithm used to fit the data.","ipynb",6),
(14,"report contains ample code comments","Your code contains code comments that are helpful to the reader in understanding what each blocks/lines of code are doing.","ipynb",8),
(15,"report contains ample markdown","Notebook contains adequate markdown that documents your thought process, decision making, and navigation through the pipeline. This should be present throughout the notebook consistently, wtih not just headers, but plenty of content that guides the reader and leaves no questions or doubt as to why you did something, e.g.","ipynb",8),
(16,"presentation appropriate for audience & setting","Always be aware of the audience and setting for your presentation.  What is the appropriate level of technicality? What is the appropriate depth given audience, setting and medium in which its delivered. The way you communicate should be appropriate for the audience: volume, speed of talk, flow, professionalism. (Codeup Data Science Instructor Team, virtually delivered via jupyter notebook).","live",9),
(17,"report content is relevant","Notebook talked through step-by-step, in an understandable and meaningful way. Extraneous content in the notebook is not present. ","live",9),
(18,"report summarized in a conclusion","Your conclusion summary should addresses the questions you raised in the opening of the project, which we would want to see at the end of every final notebook. Ideally, when the deliverable is a report, the summary should tie together your analysis, the drivers of the outcome, and how you would expect your ML model to perform in the future on unseen data, in layman's terms.","ipynb",8),
(19,"conclusion contains acctionable recommendations","Your notebook should ends with a conclusion that contains actionable recommendations based on your insights and analysis to the business stakeholder(s), your simulated audience, or someone who would find this information valuable (if there is no stakeholder). Your recommendations should not be not about what to do differently with the data, but instead should be based on the business or domain you are studying.","ipynb",8),
(20,"conclusion contains next steps","Your conclusion should include next steps from a data science perspective that will assist in improving your research. Ideally, if you talk about trying more algorithms to improve performance, think about why you need to improve performance. And if the business calls for it, remember the best way to improve performance is to have better predictors/features. If you talk about gathering more data, being specific about what data you think will help you understand the problem better and why is the way to go!","ipynb",8),
(21,"conclusion communicated clearly when presenting","Presentation is concluded with a summary of what was found, recommendations, and next steps. The presentation does not just drop off after modeling, but the entire project is nicely tied up and summarized.","live",9),
(22,"presentation time limit respected","Time limit is adhered to. The time is managed well, in that there is appropriate time spent on each section. The time should not be met by talking quickly but by reducing the amount or depth of information conveyed, and by finding easier and more simplified methods to convey the more complex information. The speech should be natural, and take the time needed for the audience to consume the information. So the time is well spent when you have practiced and you have taken the extra time it takes to reduce the content in your notebook and presentation. Time should not be spent scrolling through 10's of visualizations or hundreds of lines of code.","live",9),
(23,"report runs without errors","Your final notebook should run without error. One error in a notebook can lead to the rest of it erroring out. If you have a reader who doesn't know python, they will then not be able to consume your report. ","ipynb",8),
(24,"predictions are made","A csv with predictions made from the top model developed should be submitted, as per instructions in the project spec.","csv",7),
(25,"modules created with functions for wrangling","Module(s) with user-defined functions for acquiring and preparing the data should be created. Each function contains a helpful docstring explaining what it does, its input(s) and output(s). Credentials (such as in an env.py file) are NOT included in the public repo.","py  ",3),
(26,"data split is reproducible","When splitting data into samples, someone should be able to run your code and get the same observations in the same samples, i.e. reproduce your split, because you set the random state to a seed.  There should be 3 adequately sized samples - train, validate, and test.  As a good starting point, 50%, 30%, and 20%, (or 50%, 26%, 24% for simplicity when doing the splitting) are reasonable split proportions. But that can vary depending on the number of observations you have. Test can go as low as 10% if needed.","py  ",3),
(27,"readme includes project planning","Your readme should include a project plan which helps guide both the user and yourself through the different stages of the pipeline and steps you took to get to your conclusion.","readme",0),
(28,"readme includes data dictionary","Your readme should include a data dictionary, which is important to provide in order to define and disambiguate each of the variables you are analyzing. ","readme",0),
(29,"readme includes steps to reproduce","Your readme should include useful and adequate instructions for reproducing your analysis and final report. ","readme",0),
(30,"readme includes project goal(s)","Your readme should include a clear project goal that reflect on what you are trying to achieve for the business/organization (in the scenario layed out). Your goal is never just to create an algorithm or model or to purely make discoveries in exploration...it includes the why. 'My goal is to..., so that...' Your goal should be specific enough to know when you have reached it and concise enough to keep in 1-2 sentences. 'My goal is to identify key drivers of churn, which customers at risk of churn, and make recommendations for changes so that we can reduce the monthly churn rate and increase customer retention.' This helps tell you when you have reached a minimally viable product (including a presentation and predictions, in this example scenario).","readme",0),
(31,"readme includes project description","Your readme should include a project description that provides context for your project, including explaining why you are tackling this project, why it is important and how it could be of use to someone else beyond just the interest or new knowledge. It dives in a bit deeper than the goals. Project description and goals should always be in your words and specific to your project, not a copy of the class project spec.","readme",0),
(32,"readme includes initial questions/hypotheses","Your readme should include initial questions and focus you are going into the analysis with. This is an important part of project planning and gives context to the reader about where you started, what were your initial ideas and thoughts, and did those play out to be true.","readme",0),
(33,"scaling performed correctly","If you are performing regression, clustering, or other algorithms that incorporate a distance metric (such as KNN), your features must be on the same scale when modeling. A scaler object must be fit on train and then transformed on all three datasets (train, validate, test).","py or ipynb",3),
(34,"clustering used in exploration","Clustering is used to further explore the drivers of your target. At least 3 combinations of features are used for identifying clusters. What you do with these clusters is up to you. Remember to see the 'Using Clusters' lesson as a refresher. You may find the clusters you build are not useful at all. Or maybe they are useful in purely analysis, in understanding and being able to explain what is going on, but you have not found them useful in your supervised model. But to determine if they are useful, you must analyze the clusters created! run statistical tests and visualize the clusters, comparing the mean log error across the different clusters. Is there a significant difference between them? Plot them! Put the log error on the y-axis, cluster on th x-axis, and visualize through a violin plot, a catplot, a swarmplot, or others. Other reminders: label your clusters with something meaningful; the numeric ID given to distinguish one cluster from another does not represent a numeric measure, so don't use those values in modeling - dummy variables are the key; you don't have to use every cluster of a clustering model as features, you can select just the one(s) that show significant relationship(s) with the target variable.","ipynb",4),
(35,"data integrity - accurate data acquired","Accurate sample was acquired from the mySQL zillow database. Properties_2017 table was used. Predictions_2017 was used to filter to properties that had a transaction during 2017 and include the target variable. Properties were then filtered down to the single family homes only. You should have ended with 52,442 properties based on that criteria. Be sure and add a conditional statement to your acquire script to read a local csv of the sample that you saved so you don't have to run the query every time you re-run your notebook!","py",3),
(36,"encoding categorical variables","If you use categorical variables as features in modeling, you must encode them to numeric values. If there is a natural order to the categories of a variable or there are only 2 distinct categories, then simple encoding works fine. If there are more than 2 categories and there is no natural order to them, dummy variables must be created. For example, encoding letter grades, A-F to 1-6 would work fine. However encoding shirt color, red, blue or green, as 1, 2, or 3 will result in the algorithm mis-interpreting your data. In the shirt color case, creating dummy variables would be required, such as is_red, is_green, etc. If you left categorical variables as categories, most ML algorithms will not be able to process the variable.","py",3),
(37,"planning with a trello board","You created a trello board with cards that broke your project down into achievable small tasks, and you used this board actively during your project to guide you swiftly through your project. A task should be small enough to take less than a couple of hours and it should be written in such a way where you know when you have completed the task.","readme",0),
(38,"including an executive summary","Your readme should include a summary which states the project goals, key findings and how they apply to the business, recommendations and next steps. If your primary deliverable is a model, it's great to also include how the model expects to perform on future data","readme",0);

CREATE TABLE projects (
	proj_id INT,
	proj_name VARCHAR(255),
	module VARCHAR(255),
	proj_spec_url VARCHAR(255),
	data_source VARCHAR(255),
	team_size INT,
	presentation_setting VARCHAR(60),
	presentation_artifact VARCHAR(60)
);

INSERT INTO projects (proj_id, proj_name, module, proj_spec_url, data_source, team_size, presentation_setting, presentation_artifact)
VALUES
(0,"skills_in_demand","fundamentals","https://ds.codeup.com/fundamentals/intro-to-data-science/#data-science-skills-in-demand","linkedin, indeed",1,"live","slide_deck"),
(1,"analyzing_churn","storytelling","","telco_churn",1,"live","slide_deck"),
(2,"classifying_churn","classification","https://ds.codeup.com/classification/project/","mysql/telco_churn",1,"live","report_notebook"),
(3,"estimating_home_value","regression","https://ds.codeup.com/regression/project/","mysql/zillow",1,"live","report_notebook"),
(4,"estimating_zestimate_error","clustering","https://ds.codeup.com/clustering/project/","mysql/zillow",2,"video","report_notebook"),
(5,"forecasting_sales","time_series","https://ds.codeup.com/timeseries/project/","mysql/superstore_db",2,"video","slide_deck"),
(6,"individual_project","individual_project","https://ds.codeup.com/individual-project/individual-project/","varied",1,"async_submission","report_notebook"),
(7,"anomalies_in_curriculum_access","anomaly_detection","","curriculum_access_logs",2,"email","report_notebook"),
(8,"classifying_github_readme","nlp","https://ds.codeup.com/nlp/project/","github",2,"live","slide_deck"),
(9,"capstone","capstone","https://ds.codeup.com/capstones/capstones/","varied",4,"video","slide_deck");

CREATE TABLE project_skill_possible_pts (
	proj_id INT,
	skill_id INT,
	possible_pts DECIMAL (5,2)
);

INSERT INTO project_skill_possible_pts (proj_id, skill_id, possible_pts)
values
(2,0,2),
(3,0,2),
(4,0,2),
(2,1,3),
(3,1,3),
(4,1,2),
(6,1,3),
(2,2,2),
(3,2,2),
(4,2,2),
(6,2,2),
(2,3,3),
(3,3,3),
(4,3,3),
(6,3,3),
(2,4,6),
(3,4,6),
(4,4,6),
(6,4,6),
(2,5,6),
(3,5,6),
(4,5,5),
(6,5,6),
(2,6,6),
(3,6,6),
(4,6,5),
(6,6,6),
(2,7,6),
(3,7,6),
(4,7,6),
(6,7,7),
(2,8,1),
(3,8,1),
(4,8,1),
(6,8,1),
(2,9,1),
(3,9,1),
(4,9,1),
(6,9,1),
(2,10,1),
(3,10,1),
(4,10,1),
(6,10,1),
(2,11,2),
(3,11,2),
(4,11,2),
(6,11,2),
(2,12,2),
(3,12,2),
(4,12,2),
(6,12,2),
(2,13,3),
(3,13,3),
(4,13,3),
(6,13,3),
(2,14,6),
(3,14,6),
(4,14,6),
(6,14,7),
(2,15,6),
(3,15,6),
(4,15,6),
(6,15,7),
(2,16,2),
(3,16,2),
(4,16,2),
(2,17,2),
(3,17,2),
(4,17,2),
(2,18,2),
(3,18,2),
(4,18,2),
(6,18,2),
(2,19,2),
(3,19,2),
(4,19,2),
(6,19,2),
(2,20,2),
(3,20,2),
(4,20,2),
(6,20,2),
(2,21,2),
(3,21,2),
(4,21,2),
(2,22,2),
(3,22,2),
(4,22,2),
(2,23,6),
(3,23,6),
(4,23,5),
(6,23,6),
(2,24,5),
(2,25,3),
(3,25,3),
(4,25,3),
(6,25,3),
(2,26,1),
(3,26,1),
(4,26,1),
(2,27,2),
(3,27,2),
(4,27,2),
(6,27,2),
(2,28,2),
(3,28,2),
(4,28,2),
(6,28,2),
(2,29,2),
(3,29,2),
(4,29,2),
(6,29,2),
(2,30,3),
(3,30,3),
(4,30,2),
(6,30,3),
(2,31,3),
(3,31,3),
(4,31,2),
(6,31,3),
(2,32,3),
(3,32,2),
(4,32,2),
(6,32,3),
(3,33,3),
(4,33,3),
(6,33,4),
(4,34,6),
(3,35,3),
(4,35,3),
(6,36,3),
(6,37,3),
(6,38,3);


CREATE TABLE project_skill_requirement_pts (
	skill_id INT,
	proj_id INT,
	req_id INT,
	req_pts DECIMAL (5,2)
);

INSERT INTO project_skill_requirement_pts (skill_id, proj_id, req_id, req_pts)
VALUES
(0,2,0,2),
(0,2,1,0),
(1,2,2,3),
(1,2,3,0),
(1,2,4,1),
(2,2,5,0),
(2,2,6,2),
(3,2,12,3),
(3,2,13,2),
(3,2,7,0),
(3,2,10,1),
(4,2,20,6),
(4,2,14,4),
(4,2,18,3),
(4,2,17,2),
(4,2,16,0),
(4,2,15,1),
(5,2,25,6),
(5,2,23,3),
(5,2,21,0),
(5,2,22,2),
(6,2,30,6),
(6,2,27,0),
(6,2,28,3),
(7,2,32,6),
(7,2,35,3),
(7,2,34,0),
(7,2,33,2),
(8,2,36,0),
(8,2,37,1),
(9,2,38,1),
(9,2,39,0),
(10,2,40,1),
(10,2,41,0),
(11,2,44,2),
(11,2,42,0),
(11,2,43,1),
(12,2,45,2),
(12,2,46,0),
(13,2,47,3),
(13,2,49,0),
(14,2,51,6),
(14,2,52,0),
(15,2,53,6),
(15,2,54,0),
(16,2,55,0),
(16,2,56,2),
(17,2,57,2),
(17,2,58,0),
(18,2,59,0),
(18,2,60,2),
(19,2,61,0),
(19,2,62,2),
(20,2,63,2),
(20,2,64,0),
(21,2,65,2),
(21,2,66,0),
(22,2,67,0),
(22,2,68,2),
(23,2,69,6),
(23,2,70,0),
(24,2,71,0),
(24,2,72,5),
(24,2,73,3),
(25,2,74,3),
(25,2,75,1),
(25,2,76,0),
(26,2,77,0),
(26,2,78,1),
(27,2,79,2),
(27,2,80,0),
(28,2,81,0),
(28,2,82,2),
(29,2,83,2),
(29,2,84,0),
(30,2,86,3),
(30,2,85,0),
(31,2,87,3),
(31,2,88,0),
(32,2,90,3),
(32,2,89,0),
(0,3,0,2),
(0,3,1,0),
(1,3,2,3),
(1,3,3,0),
(1,3,4,1),
(2,3,5,0),
(2,3,6,2),
(3,3,12,3),
(3,3,7,0),
(3,3,13,2),
(3,3,10,1),
(4,3,20,6),
(4,3,14,4),
(4,3,18,3),
(4,3,16,0),
(4,3,17,2),
(4,3,15,1),
(5,3,25,6),
(5,3,21,0),
(5,3,23,3),
(5,3,22,2),
(6,3,30,6),
(6,3,27,0),
(6,3,28,3),
(7,3,32,6),
(7,3,35,3),
(7,3,34,0),
(7,3,33,2),
(8,3,36,0),
(8,3,37,1),
(9,3,38,1),
(9,3,39,0),
(10,3,40,1),
(10,3,41,0),
(11,3,44,2),
(11,3,42,0),
(11,3,43,1),
(12,3,45,2),
(12,3,46,0),
(13,3,47,3),
(13,3,49,0),
(14,3,51,6),
(14,3,52,0),
(15,3,53,6),
(15,3,54,0),
(16,3,55,0),
(16,3,56,2),
(17,3,57,2),
(17,3,58,0),
(18,3,59,0),
(18,3,60,2),
(19,3,61,0),
(19,3,62,2),
(20,3,63,2),
(20,3,64,0),
(21,3,65,2),
(21,3,66,0),
(22,3,67,0),
(22,3,68,2),
(23,3,69,6),
(23,3,70,0),
(25,3,74,3),
(25,3,76,0),
(25,3,75,1),
(26,3,77,0),
(26,3,78,1),
(27,3,79,2),
(27,3,80,0),
(28,3,81,0),
(28,3,82,2),
(29,3,83,2),
(29,3,84,0),
(30,3,86,3),
(30,3,85,0),
(31,3,87,3),
(31,3,88,0),
(32,3,89,0),
(32,3,90,2),
(33,3,91,3),
(33,3,93,1),
(33,3,94,0),
(35,3,103,3),
(35,3,100,2),
(35,3,101,0),
(35,3,102,1),
(0,4,0,2),
(0,4,1,0),
(1,4,2,2),
(1,4,3,0),
(1,4,4,1),
(2,4,5,0),
(2,4,6,2),
(3,4,12,3),
(3,4,7,0),
(3,4,13,2),
(3,4,10,1),
(4,4,20,6),
(4,4,14,4),
(4,4,16,0),
(4,4,18,3),
(4,4,17,2),
(4,4,15,1),
(5,4,21,0),
(5,4,25,5),
(5,4,23,3),
(5,4,22,2),
(6,4,27,0),
(6,4,30,5),
(6,4,28,3),
(7,4,32,6),
(7,4,34,0),
(7,4,35,3),
(7,4,33,2),
(8,4,36,0),
(8,4,37,1),
(9,4,38,1),
(9,4,39,0),
(10,4,40,1),
(10,4,41,0),
(11,4,44,2),
(11,4,42,0),
(11,4,43,1),
(12,4,45,2),
(12,4,46,0),
(13,4,48,3),
(13,4,50,0),
(14,4,51,6),
(14,4,52,0),
(15,4,53,6),
(15,4,54,0),
(16,4,55,0),
(16,4,56,2),
(17,4,57,2),
(17,4,58,0),
(18,4,59,0),
(18,4,60,2),
(19,4,61,0),
(19,4,62,2),
(20,4,63,2),
(20,4,64,0),
(21,4,65,2),
(21,4,66,0),
(22,4,67,0),
(22,4,68,2),
(23,4,70,0),
(23,4,69,5),
(25,4,74,3),
(25,4,76,0),
(25,4,75,1),
(26,4,77,0),
(26,4,78,1),
(27,4,79,2),
(27,4,80,0),
(28,4,81,0),
(28,4,82,2),
(29,4,83,2),
(29,4,84,0),
(30,4,85,0),
(30,4,86,2),
(31,4,88,0),
(31,4,87,2),
(32,4,89,0),
(32,4,90,2),
(33,4,92,3),
(33,4,94,0),
(33,4,93,1),
(34,4,97,6),
(34,4,96,5),
(34,4,98,2),
(34,4,95,1),
(34,4,99,0),
(35,4,103,3),
(35,4,101,0),
(35,4,100,2),
(35,4,102,1),
(1,6,2,3),
(1,6,4,1),
(1,6,3,0),
(2,6,6,2),
(2,6,5,0),
(3,6,11,3),
(3,6,8,3),
(3,6,9,2),
(3,6,10,1),
(3,6,7,0),
(4,6,20,6),
(4,6,18,3),
(4,6,17,2),
(4,6,19,0),
(5,6,26,6),
(5,6,24,3),
(5,6,21,0),
(6,6,31,6),
(6,6,29,3),
(6,6,27,0),
(7,6,34,7),
(7,6,35,3),
(7,6,33,2),
(7,6,34,0),
(8,6,37,1),
(8,6,36,0),
(9,6,38,1),
(9,6,39,0),
(10,6,40,1),
(10,6,41,0),
(11,6,44,2),
(11,6,43,1),
(11,6,42,0),
(12,6,45,2),
(12,6,46,0),
(13,6,47,3),
(13,6,49,0),
(14,6,51,7),
(14,6,52,0),
(15,6,53,7),
(15,6,54,0),
(18,6,60,2),
(18,6,59,0),
(19,6,62,2),
(19,6,61,0),
(20,6,63,2),
(20,6,64,0),
(23,6,69,6),
(23,6,70,0),
(25,6,74,3),
(25,6,75,1),
(25,6,76,0),
(27,6,79,2),
(27,6,80,0),
(28,6,82,2),
(28,6,81,0),
(29,6,83,2),
(29,6,84,0),
(30,6,86,3),
(30,6,85,0),
(31,6,87,3),
(31,6,88,0),
(32,6,90,3),
(32,6,89,0),
(33,6,91,4),
(33,6,93,2),
(33,6,94,0),
(36,6,105,3),
(36,6,106,1),
(36,6,104,0),
(37,6,107,3),
(37,6,108,2),
(37,6,109,0),
(38,6,111,3),
(38,6,110,0);

CREATE TABLE skill_requirements (
	req_id INT,
	skill_id INT,
	req_name VARCHAR(255),
	req_desc TEXT
);

INSERT INTO skill_requirements (req_id, skill_id, req_name, req_desc)
VALUES
(0,0,"Great Intro","You kicked off your presentation by introducing yourself and a one-liner of what your project is about."),
(1,0,"Intro missing key items","You either didn't introduce yourself, your project, or both."),
(2,1,"Functions used with md documentation.","You called the functions from modules that you created to wrangle data in your report, and you included, in your final notebook, a markdown cell, explaining the steps you took to prepare the data and why."),
(3,1,"Prep module not used.","You did not utilize the functions in your prepare.py or wrangle.py module to wrangle the data. The purpose for building modules is to import functions into your notebook reducing clutter in the final report/notebook."),
(4,1,"Missing md documentation, but functions used.","You called the functions from modules that you created to wrangle data in your report, but you did not include, in your final notebook, a markdown cell, explaining the steps you took to prepare the data."),
(5,2,"Issues with handling missing values","Improper, incomplete, or uncommunicated methods of handling missing values. You either improperly fit the imputer to your entire dataset (not just train), you did not document your decision, or your logic wasn't sound."),
(6,2,"Sound handling of missing values","You handled missing values by imputing or removing them in a logical and communicated way. You correctly handled missing values using a sound logic that was communicated via markdown documentation. You correctly used either the training data or the entire dataset to impute (given your method(s) for filling missing values)."),
(7,3,"No Splits OR Late with Two Samples","You failed to split your data into train, test, and validate samples. -OR- You split into only 2 samples (missing validate), and you did not split your data at the appropriate time. Data should be split prior to exploration of variable relationships. In addition, imputers, scalers, feature elimination, and selection algorithms should all be run after the split, so that they are fit on train and transform validate and test."),
(8,3,"No random state set.","Your data split is not reproducable because you did not set the random_state argument in your train_test_split() function to a seed (any integer). This means that someone won't be able to reproduce your work exactly, which is very important in research and analysis."),
(9,3,"No validate sample.","You split your data, but into only 2 samples. It's important to have a validate sample to test for overfitting of any models. Then the test can be used to estimate how the final model will do in the future on unseen data."),
(10,3,"Split late, Three Samples","You did not split your data at the appropriate time. Data should be split prior to exploration of variable relationships. In addition, imputers, scalers, feature elimination, and selection algorithms should all be run after the split, so that they are fit on train and transform validate and test."),
(11,3,"Split reproducible & timely","Your data was split into 3 adequately sized samples - train, validate, and test. Data is split at the right time in your process, and your data split is reproducible because you set the random state to a seed."),
(12,3,"Three Samples Before Exploring","Your data was split into three samples before exploring the interaction of variables, imputing, scaling, or running feature elimination/selection algorithms."),
(13,3,"Two Samples Before Exploring","You split your data into only two samples. It's important to have a validate sample to test for overfitting of any models. Then the test can be used to estimate how the final model will do in the future on unseen data. You did a good job of splitting before exploring the interaction of variables, imputing, scaling, or running feature elimination/selection algorithms."),
(14,4,"Missing 1 Q&A","You called out only three of the questions you asked of the data and provided a clear answer using natural language in markdown cells in your final report."),
(15,4,"Missing 2 Q&A","You called out only two of the questions you asked of the data and provided a clear answer using natural language in markdown cells in your final report."),
(16,4,"Missing 3-4 Q&A's","Majority of viz's/tests you presented in final report are not preceded with a question or goal and are not summarized with an answer/conclusion in a natural language."),
(17,4,"Missing A's/Has Q's","Questions are not answered/conclusions not drawn in your final report in a way you would communicate to all audiences. Answering with 'reject the null hypothesis' is not a satisfactory way to summarize the takeaway."),
(18,4,"Missing Q's/Has A's","Viz's/tests end with takeways, but they are not introduced with a clear question or goal of the visualization/test"),
(19,4,"viz's/tests are NOT wrapped with a Q/A","Majority of viz's/tests are not preceded with a question or goal and summarized with an answer/conclusion in a natural language."),
(20,4,"Viz's/tests wrapped in a formed Q & A","You called out at least four of the questions you asked of the data and provided a clear answer using natural language in markdown cells in your final report."),
(21,5,"<3 visualizations created. < 50% of questions are followed by a chart.","Visualizations shown do not answer questions clearly or are not tied to clearly stated takeaways. In a report, the visualizations included should answer questions and takeaways should be stated regarding drivers of your outcome. Takeaways or conclusions are written in markdown cells in natural, non-statistical language. Ideally, you want to explain what the takeaway is, right after or before the visual. All statistical tests should be supported by a visualization."),
(22,5,">7 Vizs","Visualizations shown do not answer questions clearly, are not tied to clearly stated takeaways, do not provide a specified context, or are misleading or incorrect in their representation. In a report, the included visualizations should answer questions, provide a specific context, or support a statistical test, and the included charts should be discussed or mentioned in the presentation (if applicable)."),
(23,5,"3-4 Vizs","Only three or four visualizations included. ncluded visualizations should be tied to specific statements/questions and takeaways/answers (with or without a statistical test) or set the context for the target or other key variable. All statistical tests should be supported by a visualization."),
(24,5,"3-6 visualzations created, 50-90% of questions are followed by a chart.",""),
(25,5,"5-7 Vizs","Between five and seven visualizations included. Included visualizations should be tied to specific statements/questions and takeaways/answers (with or without a statistical test) or set the context for the target or other key variable. Including more than seven visualizations in the final report typically indicates some are extraneous."),
(26,5,"Visualizations created to answer all questions. (at least 6).","In a final notebook/report, the visualizations included should answer questions and takeaways should be stated in natural, non-statistical language for each visualization you include, right after or before the visual. If there is nothing to say about a visualization, whether its the context it provides or the answer to a question, then the chart does not need to be included in the final notebook. Charts that are in the final notebook should have titles and labels that are descriptive and useful for the end user/reader of the report."),
(27,6,"No statistical tests, or all used/interpreted incorrectly","Statistical tests were not performed or were used or interpreted incorrectly."),
(28,6,"1 accurate test included","You correctly utilize only one statistical test (correct variables, conclusions drawn, no assumptions violated, and proper conclusions reached)"),
(29,6,"1-2 statistical tests used and interpreted correctly","1-2 statistical tests are utilized correctly (correct variables, conclusions drawn, no assumptions violated, and proper conclusions reached)"),
(30,6,"2 accurate tests included","You correctly utilize at least two statistical tests (correct variables, conclusions drawn, no assumptions violated, and proper conclusions reached)."),
(31,6,"3+ statistical tests used and interpreted correctly","3+ Statistical tests are utilized correctly (correct variables, conclusions drawn, no assumptions violated, and proper conclusions reached)"),
(32,7,"Analysis Summary + Features","Summary of analysis includes key takeaways from the questions answered in explore, and documentation of the features that will be tried out in modeling and why, and which features will not move forward and why. Well done!"),
(33,7,"Feature summary missing, includes key takeaways.","Documentation of the features that will be tried out in modeling and why, and which features will not move forward and why is missing, but you did include key takeaways from your analysis."),
(34,7,"Lacking Summary + Features.","Summary of analysis lacks key takeaways and documentation of feature selection decisions."),
(35,7,"Missing key takeaways, Features included","Summary is lacking takeaways from your exploration. You did include a list of which features were moving forward and why, and which ones were not and why."),
(36,8,"Baseline predictions not made/evaluated","You did not make baseline predictions and evaluate the performance. Establishing a baseline prediction method that uses no features because it tells you if having a model has any value. If any model you build does not perform as well as a baseline that uses no features, then your features are not significant drivers of the outcome."),
(37,8,"Baseline predictions evaluated","You made baseline predictions and evaluated the performance to measure your models against. Establishing a baseline prediction method that uses no features because it tells you if having a model has any value. If any model you build does not perform as well as a baseline that uses no features, then your features are not significant drivers of the outcome."),
(38,9,"All models evaluated on train","All models evaluated on train: models are always evaluated on train because it is a sample of data we have to see how the model performs. We should never skip straight to validate. We would be missing out on valuable observations."),
(39,9,"Not all models evaluated on train","One or more models were not evaluated on train: models are always evaluated on train because it is a sample of data we have to see how the model performs. We should never skip straight to validate. We would be missing out on valuable observations."),
(40,10,"Top models evaluated on validate","Your top models are evaluated with the validate sample to check for overfitting."),
(41,10,"Models not evaluated on validate dataset","Your top models are not evaluated with a validation sample dataset. It is important to use the validate sample for checking for any overfitting that may have occurred when fitting the model on train."),
(42,11,"Eval methods not documented","You did NOT explicitly identify what metric(s) you used to evaluate your models and why. If you considered multiple metrics, you did not explain how you selected a metric when one was better for model A and another is better for model B."),
(43,11,"Metric(s) used is not appropriate","You identified how you evaluated your models, but the method selected was not appropriate for the problem at hand."),
(44,11,"Eval metric(s) is clear and proper","You identified what metric(s) you used to evaluate your models and why. If you considered multiple metrics, you explained how you selected a metric when one was better for model A and another is better for model B."),
(45,12,"final model evaluated on test","Top model evaluated on test: we evaluate one last time on test in order to provide an estimate as to how we expect the model to perform in the future, in production, on data it has never seen."),
(46,12,"multiple models or no model evaluated on test","Your top performing model, and only your top performing model should be evaluated on your test dataset. The purpose of having a test dataset to evaluate only the final model on is to have an estimate of how the model will perform in the future on data it has never seen."),
(47,13,"Developed 3+ Unique Models","You developed at least 3 unique models. Models can be different based on the features used, the hyperparameters selected, and/or the algorithm used to fit the data,"),
(48,13,"Developed 4+ Unique Models","You developed at least 4 unique models. Models can be different based on the features used, the hyperparameters selected, and/or the algorithm used to fit the data,"),
(49,13,"<3 Unique Models","You did not develop at least 3 unique models. Models can be different based on the features used, the hyperparameters selected, and/or the algorithm used to fit the data,"),
(50,13,"Less than 4 Unique Models","You did not develop at least 4 unique models."),
(51,14,"Adequate comments","Your code contains code comments that are helpful to the reader in understanding what your blocks/lines of code are doing."),
(52,14,"Need more code comments","Your code needs more commenting to help the reader understand what blocks/lines of code are doing."),
(53,15,"Adequate md documentation","Notebook contains adequate markdown that documents your thought process, navigating through the pipeline. This helps your reader not get lost in the details."),
(54,15,"Need more md documentation","Your final report/notebook needs more markdown that documents your thought process and helps navigate the reader/end-user through the report. This helps your reader not get lost in the details."),
(55,16,"Improvement needed","Improvement needed in your communication consideration toward the audience and setting for the presentation of this project. You may have gone into too much depth in some areas, communication may need to be more professional, volume or speed of your talk may need some adjustment, or the presentation (whether via slides or notebook) was hard to see given the setting it was delivered in."),
(56,16,"Considered audience/setting","You clearly considered the audience and setting in which the presenation was delivered. The language was professional, volume and speed of talk was appropriate, as was level of depth, and it was easy to follow you throughout the presentation."),
(57,17,"Notebook matched presentation","Notebook was clean and relevant such that what was talked about what easy to see in the notebook, and what was in the notebook was relevant information that was included in the presentation."),
(58,17,"Notebook or presentation lacked organization or harmony","Notebook was NOT talked through in a step-by-step, understandable and meaningful way, highlighting the key steps and discoveries. This can happen with the final notebook contains too much information that may have been relevant in your discovery, but is not relevant for the final report, such as plots of all the distributions, e.g. What is in the notebook should be talked about and what is talked about, should be the primary content of the notebook."),
(59,18,"Missing Summary","Your conclusion is missing a summary that brings everything full circle and addresses the questions you raised in the opening of the project. A summary is not the evaluation outcome on the test dataset, it should tie together your analysis, the drivers of the outcome, and how you would expect your ML model to perform in the future on unseen data, in layman's terms."),
(60,18,"Includes summary","Your conclusion summary addresses the questions you raised in the opening of the project, which we would want to see at the end of every report notebook. Ideally, when the deliverable is a report such as this, the summary should tie together your analysis, the drivers of the outcome, and how you would expect your ML model to perform in the future on unseen data, in layman's terms."),
(61,19,"Missing actionable recommendations","In addition to the summary, the conclusion should always include actionable recommendations based on your insights and analysis to your simulated audience, or someone who would find this information valuable. Recommendations are not about what to do differently with the data, but instead are based on the business or domain you are studying."),
(62,19,"Includes recommendations","In addition to your summary, you included actionable recommendations based on your insights and analysis to your simulated audience, or someone who would find this information valuable. Your recommendations were not about what to do differently with the data, but instead are based on the business or domain you are studying. Nice work."),
(63,20,"includes next steps","Your conclusion includes next steps from a data science perspective that will assist in improving your research. Ideally, if you talk about trying more algorithms to improve performance, think about why you need to improve performance. And if the business calls for it, remember the best way to improve performance is to have better predictors/features. If you talk about gathering more data, being specific about what data you think will help you understand the problem better and why is the way to go!"),
(64,20,"Missing next steps","Your conclusion should also include next steps are steps from a data science perspective that will assist in finding more insights. If you talk about trying more algorithms to improve performance, think about why you need to improve performance. And if the business calls for it, remember the best way to improve performance is to have better predictors/features, not throwing more algorithms at it. If you talk about gathering more data, be more specific, what data do you think will help you understand the problem better and why."),
(65,21,"Conclusion with summary","Your presentation concluded with a summary of what was found, recommendations, and next steps."),
(66,21,"No Final Summary","Your presentation lacked a summary of what was found, recommendations, and next steps."),
(67,22,"time not well planned",""),
(68,22,"timely and planned",""),
(69,23,"No Errors","Your final notebook runs without error."),
(70,23,"Errors halting progress","Your final report couldn't be reproduced because it was halted due to errors."),
(71,24,"csv not submitted","A csv with predictions made were NOT submitted, as per instructions in the project spec."),
(72,24,"csv with predictions & probabilities","A csv with predictions made were submitted, as per instructions in the project spec."),
(73,24,"csv missing 0/1 predictions or probabilities","A csv with predictions or probabilities made were submitted, but did not include both predictions AND probabilities."),
(74,25,"Modules with functions using docstrings.","Module(s) with functions for acquiring and preparing the data are created. Functions include useful docstrings (beyond the docstrings of functions written and shared by instructors)"),
(75,25,"Modules with functions, but limited docstrings","Module(s) with functions for acquiring and preparing the data are created. Many functions, beyond the docstrings of functions written and shared by instructors, do NOT include useful docstrings."),
(76,25,"Missing functions, or env file in github","Module(s) with functions for acquiring and preparing the data are missing OR your env.py file containing credentials was pushed to github, leading to a security risk."),
(77,26,"No RandomState set","Your split is not reproducible because you did not set the random_state to a seed."),
(78,26,"RandomState set","Your split is reproducible becuase you set the random state to a seed."),
(79,27,"Includes the project 'How'","Your readme includes a project plan which helps guide both the user and yourself through the different stages of the pipeline and steps you took to get to your conclusion "),
(80,27,"Missing the 'How'","Your readme is missing a complete project plan which helps guide both the user and yourself through the different stages of the pipeline and steps you took to get to your conclusion."),
(81,28,"Missing a complete and accurate data dictionary","You are missing a complete and accurate data dictionary."),
(82,28,"Includes complete data dictionary","Your readme includes a complete and accurate data dictionary"),
(83,29,"Complete instructions to reproduce","Reproducible with ease!"),
(84,29,"Instructions lacking","You were either missing the steps to reproduce or the steps you did provide were not adequate for reproduction of your project with data, modules and notebook."),
(85,30,"Goals missing, incomplete, or inaccurate.","You did not state clear and concise project goals, including the 'so what'."),
(86,30,"Goals include what and why","You stated clear and concise project goals and included the 'so what'."),
(87,31,"Project description provides context.","Project description provides context and explains the 'whys' to your project. It is NOT a copy of the class project spec."),
(88,31,"Project description missing, incomplete or copy of spec.","You are missing a project description, it does not give the context and 'whys' of the project, OR it is a copy of the class project spec."),
(89,32,"No initial questions, discussion of areas of focus for analysis.","In your readme, you did not discuss the initial questions and focus you went into the analysis with."),
(90,32,"Initial questions, areas of focus for exploration are discussed","In your readme, you discussed the initial questions and focus you are going into the analysis with."),
(91,33,"Scaling performed correctly or not necessary","You correctly scaled your data if it was needed."),
(92,33,"Scaling performed correctly","You correctly scaled your data, and used scaled data in clustering and regression."),
(93,33,"Scaling fit on entire dataset","You scaled your data; however, you fit the scaler on the entire dataset instead of just the train. This can lead to overfitting because you are using data you should not have seen in creating your features."),
(94,33,"Scaling not performed when needed.","You used regression, clustering, or other algorithms that incorporated a distance metric, such as KNN, and because you didn't use scaled features, the algorithms did not perform as they should."),
(95,34,"1-2 clustering models, NOT explored","You developed 1 or 2 clustering models and did NOT explore the relationship of those clusters to the target variable."),
(96,34,"1-2 clustering models + explored","You developed 1 or 2 clustering models and explored the relationship of those clusters to the target variable."),
(97,34,"3 clustering models + explored","You developed 3 clustering models and explored the relationship of those clusters to the target variable."),
(98,34,"3 clustering models, NOT explored","You developed 3 clustering models but did NOT explore the relationship of those clusters to the target variable."),
(99,34,"No clustering","You did not develop any clustering models."),
(100,35,"Not optimal performance","You created unnecessary bandwidth issues that can impact others by either not using SQL to filter the rows (and reading in 1M+ properties, e.g.) or by not adding a conditional statement in your acquisition script and reading a local copy once you have acquired the data already."),
(101,35,"No SQL","You did not use SQL to acquire the data."),
(102,35,"Errors in Query","Your SQL query didn't filter accurately due to errors in the query, e.g. join errors."),
(103,35,"52k properties.","Your SQL query returned 52,442 properties...Single Family Properties which had a transaction during 2017."),
(104,36,"Encoded/Dummy variables not created when needed.","- You did not create encoded or dummy variables when it was necessary to use the feature in modeling."),
(105,36,"Encoding performed correctly or not necessary","You correctly encoded your categorical variables when necessary."),
(106,36,"Simple encoding when no natural order to variable categories","You encoded a variable that had more than 2 categories and no natural order, Therefore, you model interprets the feature categories incorrectly, where 1 is greater than 0, 3 is greater than 0, 1, and 2, etc. When in actuality, these are just distinct categories. Variables such as this should be turned into dummy variables instead."),
(107,37,"Tasks are well written, board is used.","Board created & used, tasks of adequate size and detail."),
(108,37,"Tasks need refining","You created the board, but the tasks needed a little work to make it useful"),
(109,37,"Trello board not created, used or shared.","You either did not create a trello board, provide access to it, or did not use it during this project."),
(110,38,"Lacking components of executive summary","You are missing an executive summary or you have one, but are missing one or more of the key components: project goals, key findings in analysis, and recommendations for your business stakeholders."),
(111,38,"Complete and concise executive summary","Your summary communicates project goals, key findings in analysis, and recommendations for your business stakeholders.");

CREATE TABLE pipeline (
	pipeline_id INT,
	pipeline_name VARCHAR(60)
);

INSERT INTO pipeline (pipeline_id, pipeline_name) VALUES
(0,"plan"),
(1,"acquire"),
(2,"prepare"),
(3,"wrangle"),
(4,"explore"),
(5,"preprocess"),
(6,"model"),
(7,"predict"),
(8,"report"),
(9,"present"),
(10,"deploy"),
(11,"monitor");


CREATE TABLE deliverables (
	deliverable_id INT,
	deliverable_name VARCHAR(60)
);

INSERT INTO deliverables (deliverable_id, deliverable_name)
VALUES
(0,"acquire.py"),
(1,"charts.tableau"),
(2,"dashboard"),
(3,"data.sql"),
(4,"email"),
(5,"github repo"),
(6,"practice.video"),
(7,"predictions.csv"),
(8,"prepare.py"),
(9,"presentation.live"),
(10,"presentation.video"),
(11,"readme.md"),
(12,"report.ipynb"),
(13,"slides"),
(14,"wrangle.py");

CREATE TABLE project_deliverables (
	proj_id INT,
	deliverable_id INT
);

INSERT INTO project_deliverables (proj_id, deliverable_id)
VALUES
(2,0),
(3,0),
(1,1),
(7,4),
(1,6),
(9,6),
(2,7),
(2,8),
(3,8),
(0,9),
(1,9),
(2,9),
(3,9),
(8,9),
(0,13),
(1,13),
(5,13),
(8,13),
(9,13),
(4,13),
(5,13),
(9,13),
(2,11),
(3,11),
(4,11),
(5,11),
(6,11),
(7,11),
(8,11),
(9,11),
(2,12),
(3,12),
(4,12),
(5,12),
(6,12),
(7,12),
(8,12),
(9,12),
(4,14),
(5,14),
(6,14),
(7,14),
(8,14);
