DROP TABLE IF EXISTS mpg;

CREATE TABLE mpg (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    manufacturer, VARCHAR(255) NOT NULL,
    model, VARCHAR(255) NOT NULL,
    displ, FLOAT NOT NULL,
    year, INT UNSIGNED NOT NULL,
    cyl, INT UNSIGNED NOT NULL,
    trans, VARCHAR(255) NOT NULL,
    drv, VARCHAR(10) NOT NULL,
    cty, INT UNSIGNED NOT NULL,
    hwy, INT UNSIGNED NOT NULL,
    fl, VARCHAR(10) NOT NULL,
    class, VARCHAR(255) NOT NULL
);