# Small script to find  mismatches between the table of contents and files that
# are present in the content/ directory and those referenced in the table of
# contents.
# Only works for files with a .ipynb or .md extension.
from glob import glob
import re

with open('table-of-contents.yml') as f:
    lines = f.read().split('\n')
toc_files = [
    re.sub(r'^.*:\s*', 'content/', line)
    for line in lines
    if line.endswith('.md') or line.endswith('.ipynb')
]
toc_files.remove('content/index.md') # this is autogenerated
toc_files = set(toc_files)

files_on_disk = (
    glob('content/**/*.md', recursive=True)
    + glob('content/**/*.ipynb', recursive=True)
)
files_on_disk = set([f.replace('.ipynb', '.md') for f in files_on_disk])

for f in sorted(list(files_on_disk.difference(toc_files))):
    print(f'{f} is present in the content/ directory, but is not referenced in the table of contents')

print('===')
for f in sorted(list(toc_files.difference(files_on_disk))):
    f = f.replace('.md', '')
    print(f'{f} is referenced in the table of contents, but is not present in the content/ directory')
